<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>WinExe</OutputType>
    <StartupObject>Demo.WinForms.Program</StartupObject>
    <ReleaseVersion>4.0.3</ReleaseVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <UseVSHostingProcess>false</UseVSHostingProcess>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Configuration" />
    <Reference Include="System.Management" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\ExceptionReporter.WinForms\ExceptionReporter.WinForms.csproj" />
  </ItemGroup>
</Project>